apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include ".fullname" . }}
  labels:
    {{- include ".labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["get", "watch", "list", "create"]
  - apiGroups: ["apps"]
    resources: [ "daemonsets", "deployments" ]
    verbs: ["get", "watch", "list"]