apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include ".fullname" . }}
  labels:
    {{- include ".labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include ".fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include ".fullname" . }}
  apiGroup: rbac.authorization.k8s.io